spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch   #集群名字
      cluster-nodes:  localhost:9300
server:
  port: 8081
  servlet:
    context-path: /test #节点名称

#hdfs配置
hdfs:
  rpcAddress1: 192.168.247.131:9000
  rpcAddress2: 192.168.247.131:9000